# Generated by Django 5.2.4 on 2025-07-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pays_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='soussystemeenseignement',
            unique_together={('pays', 'nom')},
        ),
        migrations.RemoveField(
            model_name='soussystemeenseignement',
            name='type_systeme',
        ),
    ]
