# Generated by Django 5.2.4 on 2025-07-05 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_soussystemeenseignement_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('classe', 'nom')},
        ),
        migrations.AddField(
            model_name='matiere',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.classe'),
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='classes',
        ),
    ]
