# Generated by Django 5.2.4 on 2025-07-05 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_matiere_unique_together_matiere_classe_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecon',
            unique_together={('matiere', 'titre')},
        ),
        migrations.AlterField(
            model_name='lecon',
            name='fichier_pdf',
            field=models.FileField(upload_to='lecons/pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='classe',
        ),
    ]
